### ISSUE TITLE
Please consider reducing the amount of version override

### ISSUE THREAD

**Issue by snicoll** [pankajtandon/stripe-starter#3]
This project uses Spring Boot's dependency management with a significant amount of version override. 

These versions override will not be applied when this starter project is included in another Spring Boot project (at the standard dependency management will apply and ignore the local overrides here). There are a bunch of version overrides that look useless to me (unless I am missing something).

**Comment by pankajtandon** [comment]
Hi @snicoll ,
I've addressed all PR comments here:
https://github.com/pankajtandon/stripe-starter/pull/4

Thanks for your suggestions!

**Comment by snicoll** [comment]
Duplicate of #4
